// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using inspect_san.Models.Data;

#nullable disable

namespace inspect_san.Migrations
{
    [DbContext(typeof(InspectSanDbContext))]
    partial class InspectSanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Chef", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("AncienneteChef")
                        .HasColumnType("int");

                    b.Property<int?>("AncienneteEcole")
                        .HasColumnType("int");

                    b.Property<int?>("AncienneteEnseignement")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EcoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IdDinacope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.HasIndex("IdDinacope");

                    b.ToTable("Chefs", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Commune", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.ToTable("Communes", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Controleur", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EquipeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Controleurs", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Decision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DecideLe")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DecidePar")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("DelaiExecution")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EcoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Motif")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("RapportId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StatutExecution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TypeDecisionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("RapportId");

                    b.HasIndex("StatutExecution");

                    b.HasIndex("TypeDecisionId");

                    b.ToTable("Decisions", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Ecole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CommuneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("IdDinacope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumAgrement")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumNotification")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegimeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommuneId");

                    b.HasIndex("IdDinacope")
                        .IsUnique();

                    b.HasIndex("RegimeId");

                    b.HasIndex("Statut");

                    b.ToTable("Ecoles", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Equipe", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ChefControleurId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ChefControleurId")
                        .IsUnique();

                    b.HasIndex("Nom");

                    b.ToTable("Equipes", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.FicheControle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ChefId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EcoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Observations")
                        .HasColumnType("longtext");

                    b.Property<string>("OrdreMissionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ProduitsAutres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RecommandationPreliminaire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValideeLe")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValideePar")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChefId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EcoleId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("OrdreMissionId");

                    b.HasIndex("Statut");

                    b.ToTable("FichesControle", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.JournalEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Module");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("JournalEntries", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.NotificationItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Lu");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.OrdreMission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateEmission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateMission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DebutValidite")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EcoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EquipeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("FinValidite")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Objet")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("SigneLe")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SignePar")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EcoleId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.HasIndex("DebutValidite", "FinValidite");

                    b.ToTable("OrdresMission", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Rapport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("AccusePar")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("AccuseReceptionLe")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeposeLe")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeposePar")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("EcoleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FicheIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FicheIdsJson");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Synthese")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TransmisLe")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeposeLe");

                    b.HasIndex("EcoleId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.ToTable("Rapports", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.RapportFiche", b =>
                {
                    b.Property<string>("RapportId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FicheControleId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("RapportId", "FicheControleId");

                    b.HasIndex("FicheControleId");

                    b.ToTable("RapportFiches", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Regime", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom");

                    b.ToTable("Regimes", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Entities.TypeDecision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Actif")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Libelle")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Nom");

                    b.ToTable("TypesDecision", (string)null);
                });

            modelBuilder.Entity("inspect_san.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("ControleurId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EcoleId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Equipe")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EquipeId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ControleurId")
                        .IsUnique();

                    b.HasIndex("EcoleId");

                    b.HasIndex("EquipeId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("inspect_san.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("inspect_san.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("inspect_san.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Chef", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Ecole", "Ecole")
                        .WithMany("Chefs")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Controleur", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Equipe", "Equipe")
                        .WithMany("Controleurs")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Decision", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Ecole", "Ecole")
                        .WithMany("Decisions")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.Rapport", "Rapport")
                        .WithMany("Decisions")
                        .HasForeignKey("RapportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.TypeDecision", "TypeDecision")
                        .WithMany("Decisions")
                        .HasForeignKey("TypeDecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ecole");

                    b.Navigation("Rapport");

                    b.Navigation("TypeDecision");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Ecole", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Commune", "Commune")
                        .WithMany("Ecoles")
                        .HasForeignKey("CommuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.Regime", "Regime")
                        .WithMany("Ecoles")
                        .HasForeignKey("RegimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("inspect_san.Models.Entities.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<string>("EcoleId")
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("Avenue")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Adresse_Avenue");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Adresse_Numero");

                            b1.Property<string>("Quartier")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("Adresse_Quartier");

                            b1.HasKey("EcoleId");

                            b1.ToTable("Ecoles");

                            b1.WithOwner()
                                .HasForeignKey("EcoleId");
                        });

                    b.OwnsMany("inspect_san.Models.Entities.DocumentMeta", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Date")
                                .HasColumnType("datetime(6)");

                            b1.Property<string>("EcoleId")
                                .IsRequired()
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("varchar(250)");

                            b1.Property<string>("Taille")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("EcoleId");

                            b1.ToTable("EcoleDocuments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("EcoleId");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();

                    b.Navigation("Commune");

                    b.Navigation("Documents");

                    b.Navigation("Regime");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Equipe", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Controleur", "ChefControleur")
                        .WithMany()
                        .HasForeignKey("ChefControleurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChefControleur");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.FicheControle", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Chef", "Chef")
                        .WithMany("FichesControle")
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("inspect_san.Models.Entities.Ecole", "Ecole")
                        .WithMany("FichesControle")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.OrdreMission", "OrdreMission")
                        .WithMany("FichesControle")
                        .HasForeignKey("OrdreMissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("inspect_san.Models.Entities.PhotoMeta", "Photos", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("FicheControleId")
                                .IsRequired()
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("Legende")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("varchar(250)");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("varchar(250)");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)");

                            b1.HasKey("Id");

                            b1.HasIndex("FicheControleId");

                            b1.ToTable("FichePhotos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FicheControleId");
                        });

                    b.OwnsOne("inspect_san.Models.Entities.SectionBatiments", "SectionBatiments", b1 =>
                        {
                            b1.Property<string>("FicheControleId")
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("EtatGeneral")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Batiments_EtatGeneral");

                            b1.Property<int>("NombreBatiments")
                                .HasColumnType("int")
                                .HasColumnName("Batiments_NombreBatiments");

                            b1.Property<int>("NombreEleves")
                                .HasColumnType("int")
                                .HasColumnName("Batiments_NombreEleves");

                            b1.Property<string>("ToilettesFilles")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("Batiments_ToilettesFilles");

                            b1.Property<string>("ToilettesGarcons")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("Batiments_ToilettesGarcons");

                            b1.HasKey("FicheControleId");

                            b1.ToTable("FichesControle");

                            b1.WithOwner()
                                .HasForeignKey("FicheControleId");
                        });

                    b.OwnsOne("inspect_san.Models.Entities.SectionImpact7", "SectionImpact7", b1 =>
                        {
                            b1.Property<string>("FicheControleId")
                                .HasColumnType("varchar(64)");

                            b1.Property<string>("MontantPercu")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("Impact7_MontantPercu");

                            b1.Property<string>("ProduitsNettoyage")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("Impact7_ProduitsJson");

                            b1.Property<string>("Quantite")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("varchar(250)")
                                .HasColumnName("Impact7_Quantite");

                            b1.HasKey("FicheControleId");

                            b1.ToTable("FichesControle");

                            b1.WithOwner()
                                .HasForeignKey("FicheControleId");
                        });

                    b.Navigation("Chef");

                    b.Navigation("Ecole");

                    b.Navigation("OrdreMission");

                    b.Navigation("Photos");

                    b.Navigation("SectionBatiments")
                        .IsRequired();

                    b.Navigation("SectionImpact7")
                        .IsRequired();
                });

            modelBuilder.Entity("inspect_san.Models.Entities.OrdreMission", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Ecole", "Ecole")
                        .WithMany("OrdresMission")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.Equipe", "Equipe")
                        .WithMany("OrdresMission")
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ecole");

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Rapport", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.Ecole", "Ecole")
                        .WithMany("Rapports")
                        .HasForeignKey("EcoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ecole");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.RapportFiche", b =>
                {
                    b.HasOne("inspect_san.Models.Entities.FicheControle", "FicheControle")
                        .WithMany("RapportFiches")
                        .HasForeignKey("FicheControleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("inspect_san.Models.Entities.Rapport", "Rapport")
                        .WithMany("RapportFiches")
                        .HasForeignKey("RapportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FicheControle");

                    b.Navigation("Rapport");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Chef", b =>
                {
                    b.Navigation("FichesControle");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Commune", b =>
                {
                    b.Navigation("Ecoles");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Ecole", b =>
                {
                    b.Navigation("Chefs");

                    b.Navigation("Decisions");

                    b.Navigation("FichesControle");

                    b.Navigation("OrdresMission");

                    b.Navigation("Rapports");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Equipe", b =>
                {
                    b.Navigation("Controleurs");

                    b.Navigation("OrdresMission");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.FicheControle", b =>
                {
                    b.Navigation("RapportFiches");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.OrdreMission", b =>
                {
                    b.Navigation("FichesControle");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Rapport", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("RapportFiches");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.Regime", b =>
                {
                    b.Navigation("Ecoles");
                });

            modelBuilder.Entity("inspect_san.Models.Entities.TypeDecision", b =>
                {
                    b.Navigation("Decisions");
                });
#pragma warning restore 612, 618
        }
    }
}
